packages:
  - apps/*
  - apps/playground/*
  - packages/*

catalog:
  eslint: ^9.39.2
  stylelint: ^16.26.1
  typescript: 5.9.3
  unplugin-vue: ^7.1.0
  vite: ^7.3.0
  vite-plugin-dts: ^4.5.4
  vue: ^3.5.26
  vue-tsc: ^3.2.1

onlyBuiltDependencies:
  - esbuild
